//! Versioned BexOS guest interfaces, generated by the Bazel Rust compile action.
wasmtime::component::bindgen!({
 path: ["external/+_repo_rules+wasmtime_wasi_wit/src/p2/wit", "lib/wasm_runtime/wit"],
 with: {
  "wasi:filesystem/preopens": crate::wasi::wasi::filesystem::preopens,
  "wasi:filesystem/types": crate::wasi::wasi::filesystem::types,
  "wasi:io/streams": crate::wasi::wasi::io::streams,
  "wasi:io/poll": crate::wasi::wasi::io::poll,
  "wasi:io/error": crate::wasi::wasi::io::error,
  "wasi:sockets/network": crate::wasi::wasi::sockets::network,
  "wasi:sockets/tcp": crate::wasi::wasi::sockets::tcp,
  "wasi:sockets/udp": crate::wasi::wasi::sockets::udp,
  "wasi:sockets/ip-name-lookup": crate::wasi::wasi::sockets::ip_name_lookup,
 },
 world: "bexos:wasm/service",
 imports: { default: trappable },
 exports: { default: async },
});
