load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "debug_client",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "bexos_debug_client",
    edition = "2024",
    deps = ["//lib/debug_wire"],
)

rust_test(
    name = "debug_client_tests",
    srcs = glob(["tests/**/*.rs"]),
    crate_name = "debug_client_tests",
    edition = "2024",
    deps = [
        ":debug_client",
        "//lib/debug_wire",
    ],
)

rust_test(name = "framing_tests", crate = ":debug_client")
