//! Sustained real-session workloads. F1..F5 start after integration cleanup.
//! Logical progress and every owned mapping/lease survive fixture replacement.
use crate::{Fixture, fenced};
use bexos_graphics::{Format, Surface, effects::Effects};
use bexos_graphics_runtime::{self as rt, Mapping, flatland::Session};
use bexos_migration::{
    Error,
    codec::{Decoder, Encoder},
};
use bexos_userspace::{Channel, Memory, live_migration::Resource};
use graphics_fidl::*;
const TOTAL: u64 = 288;
#[derive(Default)]
pub struct Performance {
    pub workload: u32,
    phase: u64,
    frames: u64,
    sequence: u64,
    buffers: Vec<Mapping>,
    leases: Vec<(u64, u64)>,
}
impl Performance {
    pub fn encode(&self, w: &mut Encoder) {
        for v in [
            self.workload as u64,
            self.phase,
            self.frames,
            self.sequence,
            self.buffers.len() as u64,
        ] {
            w.word(v);
        }
        for b in &self.buffers {
            b.encode(w);
        }
        w.word(self.leases.len() as u64);
        for &(sequence, handle) in &self.leases {
            w.word(sequence);
            w.word(handle);
        }
    }
    pub fn decode(r: &mut Decoder<'_>) -> Result<Self, Error> {
        let mut s = Self {
            workload: r.word()?.try_into().map_err(|_| Error::InvalidData)?,
            phase: r.word()?,
            frames: r.word()?,
            sequence: r.word()?,
            ..Self::default()
        };
        for _ in 0..r.count(3)? {
            s.buffers.push(Mapping::decode(r)?);
        }
        for _ in 0..r.count(4)? {
            s.leases.push((r.word()?, r.word()?));
        }
        if s.workload > 5
            || s.phase > 5
            || s.frames > TOTAL
            || (s.phase != 0 && s.buffers.len() != 3)
            || s.leases.iter().any(|&(seq, h)| seq == 0 || h == 0)
        {
            return Err(Error::InvalidData);
        }
        Ok(s)
    }
    pub fn resources(&self) -> Vec<Resource> {
        self.buffers
            .iter()
            .flat_map(|b| b.resources())
            .chain(self.leases.iter().map(|l| Resource::Handle(l.1)))
            .collect()
    }
    pub fn activate(&mut self) {
        for b in &mut self.buffers {
            b.owned = true;
        }
    }
}
fn surface(format: Format) -> Surface {
    Surface {
        width: 800,
        height: 600,
        stride: 3200,
        format,
    }
}
fn config() {
    // Decode bounded protobuf varints generated by Bazel from the fixture recipe.
    let mut bytes = include_bytes!(env!("PERFORMANCE_CONFIG")).as_slice();
    let mut values = [0u64; 4];
    while !bytes.is_empty() {
        let tag = bytes[0];
        bytes = &bytes[1..];
        assert!(tag % 8 == 0 && (1..=4).contains(&(tag / 8)));
        let mut value = 0;
        let mut shift = 0;
        loop {
            let b = bytes[0];
            bytes = &bytes[1..];
            value |= ((b & 127) as u64) << shift;
            if b < 128 {
                break;
            }
            shift += 7;
            assert!(shift < 64);
        }
        values[(tag / 8 - 1) as usize] = value;
    }
    assert_eq!(values, [32, 256, 800, 600]);
}
pub fn start(f: &mut Fixture, workload: u32) {
    assert_eq!(
        f.transition.phase, 6,
        "performance requires completed client cleanup"
    );
    assert!(f.performance.phase == 0 || f.performance.phase == 5);
    config();
    // Every workload uses distinct node IDs so previous queued graphs remain valid.
    let root = 1000 + workload as u64 * 20;
    let mut client = Session::new(f.sessions[0]);
    client.create(root).unwrap();
    let mut buffers = Vec::new();
    for _ in 0..2 {
        let mut b = Mapping::new(800 * 600 * 4).unwrap();
        for p in b.bytes_mut().chunks_exact_mut(4) {
            p.copy_from_slice(&[41, 83, 167, 255]);
        }
        buffers.push(b);
    }
    let (ow, oh) = if workload == 3 { (64, 64) } else { (320, 240) };
    let mut overlay = Mapping::new(ow * oh * 4).unwrap();
    for p in overlay.bytes_mut().chunks_exact_mut(4) {
        p.copy_from_slice(&[16, 32, 64, 128]);
    }
    buffers.push(overlay);
    client
        .content(root, buffers[0].handle, surface(Format::Bgra))
        .unwrap();
    if (2..=4).contains(&workload) {
        for i in 0..8 {
            let id = root + 1 + i;
            client.create(id).unwrap();
            client.attach(root, id).unwrap();
            client
                .translation(id, 100 + i as i32 * 20, 100 + i as i32 * 10)
                .unwrap();
            client
                .content(
                    id,
                    buffers[2].handle,
                    Surface {
                        width: ow as u32,
                        height: oh as u32,
                        stride: ow as u32 * 4,
                        format: Format::Bgra,
                    },
                )
                .unwrap();
            if workload == 4 && i == 7 {
                client
                    .effects(
                        id,
                        Effects {
                            corner_radius: 8.,
                            backdrop_radius: 16,
                        },
                    )
                    .unwrap();
            }
        }
    }
    client.root(root).unwrap();
    if f.performance.phase == 5 {
        let old = 1000 + f.performance.workload as u64 * 20;
        let count = if (2..=4).contains(&f.performance.workload) {
            9
        } else {
            1
        };
        for id in (old..old + count).rev() {
            crate::call(
                &mut client.channel,
                10,
                &FlatlandSessionReleaseTransformRequest { node_id: id },
            );
        }
    }
    client.present(0).unwrap();
    let sequence = client.presentation_info().unwrap().accepted_sequence;
    f.performance = Performance {
        workload,
        phase: 1,
        sequence,
        buffers,
        ..Default::default()
    };
    bexos_userspace::log(&format!(
        "scened-workload: begin workload={workload} warmup=32 samples=256\n"
    ));
}
pub fn poll(f: &mut Fixture) {
    let p = &mut f.performance;
    if p.phase == 0 || p.phase == 5 {
        return;
    }
    p.leases
        .retain(|&(seq, handle)| match Channel(handle).try_recv() {
            Ok(m) => {
                let r = PresentationRelease::decode(&m.bytes, &[]).unwrap();
                assert_eq!(r.status, Status::Ok);
                assert_eq!(r.sequence, seq);
                Memory::close(handle).unwrap();
                false
            }
            Err(kernel_fidl::Status::ErrPeerClosed) => panic!("performance release missing"),
            Err(_) => true,
        });
    let mut client = Session::new(f.sessions[0]);
    let feedback = client.feedback().unwrap();
    assert!(
        feedback.rejected_sequence < p.sequence,
        "sustained presentation rejected"
    );
    if feedback.presented_sequence < p.sequence {
        return;
    }
    if p.phase == 4 {
        if !p.leases.is_empty() {
            return;
        }
        p.phase = 5;
        bexos_userspace::log(&format!(
            "scened-workload: complete workload={} frames={} leases=0\n",
            p.workload, p.frames
        ));
        return;
    }
    if p.phase == 1 {
        let r: ShellControlBeginMeasurementResponse = rt::call(
            &mut Channel(f.accessibility.shell),
            5,
            &ShellControlBeginMeasurementRequest {
                workload: p.workload,
            },
        )
        .unwrap();
        if r.status == Status::ErrBusy {
            return;
        }
        assert_eq!(r.status, Status::Ok);
        p.phase = 2;
    } else if p.phase == 3 {
        p.frames += 1;
        if p.frames % 32 == 0 {
            bexos_userspace::log(&format!(
                "scened-workload: progress workload={} frames={}\n",
                p.workload, p.frames
            ));
        }
        p.phase = 2;
        if p.frames == TOTAL {
            // Replace leased scanout before checking final retirement. Keep the
            // workload pixels so the host can verify them after the done marker.
            let root = 1000 + p.workload as u64 * 20;
            client
                .content(root, p.buffers[0].handle, surface(Format::Bgra))
                .unwrap();
            client.present(0).unwrap();
            p.sequence = client.presentation_info().unwrap().accepted_sequence;
            p.phase = 4;
            return;
        }
    }
    if p.leases.len() >= 3 {
        return;
    }
    let root = 1000 + p.workload as u64 * 20;
    if p.workload == 5 {
        // Alternate imports; reusing the same immutable front is not a page flip.
        client
            .content(
                root,
                p.buffers[(p.frames % 2) as usize].handle,
                surface(Format::Bgrx),
            )
            .unwrap();
    } else if p.workload == 1 {
        client
            .content(
                root,
                p.buffers[(p.frames % 2) as usize].handle,
                surface(Format::Bgra),
            )
            .unwrap();
    } else {
        // Partial workload moves only one small item. Overlap and backdrop move
        // the whole eight-layer group, forcing broad composition/effect repair.
        let count = if p.workload == 3 { 1 } else { 8 };
        for i in 0..count {
            client
                .translation(
                    root + 1 + i,
                    100 + i as i32 * 20 + (p.frames % 2) as i32,
                    100 + i as i32 * 10,
                )
                .unwrap();
        }
    }
    let (sequence, acquire, release) = fenced(&mut client.channel);
    acquire.send(&[], &[]).unwrap();
    Memory::close(acquire.0).unwrap();
    p.leases.push((sequence, release.0));
    p.sequence = sequence;
    p.phase = 3;
}
