load("//testing/e2e/qemu:qemu_e2e.bzl", "qemu_e2e_test")
load("//testing/e2e/qemu:architecture_test.bzl", "qemu_suites")
package(default_visibility = ["//visibility:public"])
qemu_e2e_test(
 tier = "extended",
 name = "wasm_e2e_test",
 src = "wasm_e2e_test.rs",
 crate_name = "wasm_e2e_test",
 deps = ["//host/debug_client", "//testing/e2e", "//tools/qemu:qemu_test"],
)
qemu_suites()
