load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("//build/platforms:architecture.bzl", "guest_select")
package(default_visibility = ["//visibility:public"])
rust_library(
    name = "elf",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "bexos_elf",
    edition = "2024",
    rustc_flags = guest_select([], ["--cfg=bexos_arch_x86_64"]),
)
rust_test(name = "elf_tests", crate = ":elf")

