#!/bin/sh
set -eu
export PYTHONDONTWRITEBYTECODE=1
if [ -n "${VENUS_LINUX_DISK:-}" ]; then
    exec python3 "$VENUS_LINUX_RUN" "$VENUS_LINUX_KERNEL" "$VENUS_LINUX_INITRAMFS" "$VENUS_LINUX_DISK"
fi
exec python3 "$VENUS_LINUX_RUN" "$VENUS_LINUX_KERNEL" "$VENUS_LINUX_INITRAMFS"
