load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "bexos_app",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "bexos_app",
    edition = "2024",
)

rust_library(
    name = "bexos_component",
    srcs = ["component.rs"],
    crate_name = "bexos_component",
    edition = "2024",
    deps = [
        "//lib/bexos_libc",
        "//lib/migration",
        "//lib/userspace",
    ],
)

alias(name = "bexos_driver_startup", actual = "//lib/userspace")
alias(name = "bexos_hardware_resource", actual = "//lib/userspace")
alias(name = "bexos_migration", actual = "//lib/migration")
alias(name = "bexos_service_binding", actual = "//lib/userspace")
alias(name = "bexos_libc", actual = "//lib/bexos_libc")

rust_library(
    name = "bexos_wasm_guest",
    srcs = ["wasm_guest.rs"],
    crate_name = "bexos_wasm_guest",
    compile_data = ["wasm.wit"],
    edition = "2024",
    rustc_env = {"CARGO_MANIFEST_DIR": "."},
    deps = ["@crates//:wit-bindgen"],
)

filegroup(name = "files", srcs = glob(["**"]))
