/* Canonical cross-language fixtures generated by the actual C authority. */
#include "include/bexos_boot_selection.h"
#include "include/bexos_journal.h"
#include <stdio.h>
#include <string.h>
int main(int argc, char** argv) {
    uint8_t trusty[96], monitor[96], state[512], next[512], request[256];
    if (argc == 2 && !strcmp(argv[1], "--step")) {
        if (fread(state, 1, 512, stdin) != 512 ||
            fread(request, 1, 256, stdin) != 256 || fgetc(stdin) != EOF) return 1;
        unsigned result = bexos_boot_next(state, request, next);
        if (result) return 2;
        return fwrite(next, 1, 512, stdout) == 512 ? 0 : 1;
    }
    if (argc != 1) return 1;
    bexos_journal_initial(trusty, 2, 1); bexos_journal_initial(monitor, 2, 2);
    if (!bexos_boot_initial(state, trusty, monitor)) return 1;
    if (fwrite(state, 1, 512, stdout) != 512) return 1;
    for (unsigned op = 2; op <= 4; ++op) {
        memset(request, 0, 256); memcpy(request, "BEXBS002", 8);
        request[8] = op; request[12] = 2; request[24] = 2;
        memcpy(request+16, state+16, 8);
        request[32] = 2; request[40] = 2; memset(request+48, 0x5a, 32); request[81] = 1;
        if (bexos_boot_next(state, request, next)) return 1;
        if (fwrite(next, 1, 512, stdout) != 512) return 1;
        memcpy(state, next, 512);
    }
    return 0;
}
