load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "user_store",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "bexos_user_store",
    edition = "2024",
)

rust_library(
    name = "user_store_host",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["std", "redb_backend"],
    crate_name = "bexos_user_store",
    edition = "2024",
    deps = [
        "//lib/redb:redb_host",
        "@crates//:redb",
    ],
)

rust_library(
    name = "user_store_bexos_std",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["std", "redb_backend"],
    crate_name = "bexos_user_store",
    edition = "2024",
    deps = [
        "//lib/redb:redb_bexos_std",
        "@crates//:redb",
    ],
)

rust_test(
    name = "user_store_tests",
    srcs = glob(["tests/**/*.rs"]),
    crate_name = "user_store_tests",
    edition = "2024",
    deps = [
        ":user_store_host",
        "//lib/crypto",
        "//lib/redb:redb_host",
    ],
)
