"""Generate the shared QEMU/firmware geometry from the bounded prototxt profile."""
from pathlib import Path
import re
import sys

FIELDS = ("transition_base", "transition_bytes", "owner_bytes", "trusty_bank_bytes", "upload_bytes", "migration_bytes", "persistent_bytes")

def parse(text):
    text = re.sub(r"#[^\n]*", "", text)
    values = {}
    while text.strip():
        match = re.match(r"\s*([a-z_]+)\s*:\s*([0-9]+)\s*", text)
        if not match or match[1] not in FIELDS or match[1] in values:
            raise ValueError("invalid or duplicate secure memory field")
        values[match[1]] = int(match[2])
        text = text[match.end():]
    if set(values) != set(FIELDS):
        raise ValueError("missing secure memory geometry")
    base, size, owner, bank, upload, migration, persistent = (values[field] for field in FIELDS)
    if any(v == 0 or v % 4096 for v in values.values()):
        raise ValueError("secure memory geometry must be page aligned")
    if base < 1 << 40 or base + size > 1 << 48:
        raise ValueError("transition RAM must be in the reserved high secure window")
    if size > 512 * 1024 * 1024 or bank < 64 * 1024 * 1024 or owner < 16 * 1024 * 1024:
        raise ValueError("invalid secure bank capacity")
    if upload < 64 * 1024 * 1024 + 64 * 1024 + 32:
        raise ValueError("upload region cannot contain the maximum signed firmware")
    if persistent < 4096 + 4 * 65 * 1024 * 1024:
        raise ValueError("persistent region cannot contain all authenticated A/B slots")
    if owner + 2 * bank + upload + migration + persistent > size:
        raise ValueError("secure regions exceed transition memory")
    return values

def generate(values):
    base, size, owner, bank, upload, migration, persistent = (values[field] for field in FIELDS)
    constants = dict(values)
    constants.update(owner_base=base, trusty_a_base=base + owner, trusty_b_base=base + owner + bank,
                     upload_base=base + owner + 2 * bank, migration_base=base + owner + 2 * bank + upload,
                     persistent_base=base + owner + 2 * bank + upload + migration)
    header = "/* Generated by Bazel from the secure platform prototxt. */\n#pragma once\n"
    header += "".join(f"#define BEXOS_{name.upper()} 0x{value:x}\n" for name, value in constants.items())
    linker = "/* Generated secure memory geometry. */\n"
    linker += "".join(f"BEXOS_{name.upper()} = 0x{value:x};\n" for name, value in constants.items())
    rust = "// Generated secure memory geometry.\n"
    rust += "".join(f"pub const {name.upper()}: u64 = 0x{value:x};\n" for name, value in constants.items())
    return header, linker, rust

if __name__ == "__main__":
    outputs = generate(parse(Path(sys.argv[1]).read_text()))
    for path, text in zip(sys.argv[2:], outputs, strict=True):
        Path(path).write_text(text)
