package(default_visibility = ["//visibility:public"])

sh_test(
    name = "manifest_services_test",
    srcs = ["manifest_services_test.sh"],
    args = [
        "--protoc",
        "$(location @protobuf//:protoc)",
        "--manifest-proto",
        "$(locations //idl:app_manifest_proto_src)",
        "--well-known-protos",
        "$(locations @protobuf//:well_known_type_protos)",
        "--",
        "$(location //drivers/d1/storage/bexos/archivefs:package_manifest)",
        "bexos.storage.archive.ArchiveManager|ArchiveManager|SINGLETON|40,41",
        "$(location //drivers/d1/storage/bexos/bexfs:package_manifest)",
        "bexos.fs.Filesystem|Filesystem|SINGLETON|30,31,32",
        "$(location //drivers/d1/storage/bexos/diskimage:package_manifest)",
        "bexos.storage.diskimage.DiskImageManager|DiskImageManager|SINGLETON|1",
        "$(location //drivers/d1/storage/nvmexpress/nvme:package_manifest)",
        "bexos.storage.block.BlockDevice|BlockDevice|MULTIPLE_INSTANCE|1,2,3,4,5",
        "bexos.power.DevicePowerControl|DevicePowerControl|MULTIPLE_INSTANCE|1",
        "$(location //drivers/d1/storage/usb/bot:package_manifest)",
        "bexos.storage.block.BlockDevice|BlockDevice|MULTIPLE_INSTANCE|1,2,3,4,5",
        "$(location //drivers/d1/usb/xhci:package_manifest)",
        "bexos.usb.host.XhciController|XhciController|MULTIPLE_INSTANCE|1,2,3,4,5,6,7,8,9",
        "$(location //drivers/d1/input/usb_hid:package_manifest)",
        "bexos.hardware.input.InputDevice|InputDevice|MULTIPLE_INSTANCE|1",
        "$(location //drivers/d1/bus/generic/pci:package_manifest)",
        "bexos.power.DevicePowerControl|DevicePowerControl|MULTIPLE_INSTANCE|1",
        "$(location //drivers/d1/serial/arm/pl011:package_manifest)",
        "bexos.power.DevicePowerControl|DevicePowerControl|MULTIPLE_INSTANCE|1",
        "$(location //drivers/d1/rtc/arm/pl031:package_manifest)",
        "bexos.time.RtcHardware|RtcHardware|SINGLETON|1,2",
    ],
    data = [
        "//drivers/d1/storage/bexos/archivefs:package_manifest",
        "//drivers/d1/storage/bexos/bexfs:package_manifest",
        "//drivers/d1/storage/bexos/diskimage:package_manifest",
        "//drivers/d1/storage/nvmexpress/nvme:package_manifest",
        "//drivers/d1/storage/usb/bot:package_manifest",
        "//drivers/d1/usb/xhci:package_manifest",
        "//drivers/d1/input/usb_hid:package_manifest",
        "//drivers/d1/bus/generic/pci:package_manifest",
        "//drivers/d1/rtc/arm/pl031:package_manifest",
        "//drivers/d1/serial/arm/pl011:package_manifest",
        "//idl:app_manifest_proto_src",
        "@protobuf//:protoc",
        "@protobuf//:well_known_type_protos",
    ],
)
