package(default_visibility = ["//visibility:public"])

alias(name = "wasm_app.bex", actual = "@bexos//testing/out_of_tree_sdk/in_tree:wasm_archive")
alias(name = "native_aarch64_app.bex", actual = "@bexos//testing/out_of_tree_sdk/in_tree:native_archive")
alias(name = "native_x86_64_app.bex", actual = "@bexos//testing/out_of_tree_sdk/in_tree:native_archive")
alias(name = "service_aarch64.bex", actual = "@bexos//testing/out_of_tree_sdk/in_tree:service_archive")
alias(name = "service_x86_64.bex", actual = "@bexos//testing/out_of_tree_sdk/in_tree:service_archive")
alias(name = "service_replacement.bex", actual = "@bexos//testing/out_of_tree_sdk/in_tree:service_replacement_archive")
alias(name = "driver_aarch64.bex", actual = "@bexos//testing/out_of_tree_sdk/in_tree:driver_archive")
alias(name = "driver_x86_64.bex", actual = "@bexos//testing/out_of_tree_sdk/in_tree:driver_archive")
alias(name = "driver_replacement.bex", actual = "@bexos//testing/out_of_tree_sdk/in_tree:driver_replacement_archive")
