load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])
filegroup(name = "sdk_files", srcs = ["BUILD.bazel"] + glob(["src/**/*.rs"]))

rust_library(
    name = "restricted_abi",
    srcs = ["src/lib.rs"],
    crate_name = "bexos_restricted_abi",
    edition = "2024",
)

rust_test(
    name = "tests",
    crate = ":restricted_abi",
)
