load("//build/rules:app_archive.bzl", "app_archive")
load("//build/rules:userspace.bzl", "app_manifest")
load("//build/rules:wasm.bzl", "wasi_component")
load("@rules_rust//rust:defs.bzl", "rust_test")
package(default_visibility = ["//visibility:public"])
wasi_component(name = "wasm", crate_name = "bexos_userui", srcs = glob(["src/**/*.rs"]), deps = ["//lib/dioxus_guest", "//lib/shell_guest", "//lib/migration", "//lib/ui/prelude"])
app_manifest(name = "manifest", src = "package/manifest.prototxt")
app_archive(name = "userui", manifest = ":manifest", entries = {"bin/userui.wasm": ":wasm"}, compression = "zstd")
app_archive(name = "replacement_archive", manifest = ":manifest", entries = {"bin/userui.wasm": ":wasm"}, compression = "zstd")
rust_test(name = "tests", srcs = glob(["src/**/*.rs"]), crate_root = "src/main.rs", edition = "2024", deps = ["//lib/dioxus_guest", "//lib/shell_guest", "//lib/migration", "//lib/ui/prelude"])
