load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "dioxus_dom",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "bexos_dioxus_dom",
    edition = "2024",
    deps = ["//lib/dioxus_scene"],
)

rust_test(
    name = "tests",
    crate = ":dioxus_dom",
)
