load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "empty_libs",
    srcs = glob(["empty_libs/*.so"]),
)

rust_library(
    rustc_flags = select({"//build/platforms:is_bexos_userspace": ["--cfg=bexos_guest"], "//conditions:default": []}),
    name = "bexos_libc",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "bexos_libc",
    edition = "2024",
    deps = [
        "//idl:fs_fidl_rust",
        "//idl:kernel_fidl_rust",
        "//idl:net_fidl_rust",
        "//lib/allocator",
        "//lib/futex_sync",
        "//lib/boot",
        "//lib/time_abi",
        "//lib/userspace",
        "@crates//:libm",
    ],
)

rust_test(
    name = "internal_tests",
    crate = ":bexos_libc",
    env = {"RUST_TEST_THREADS": "1"},
)

rust_test(
    name = "bexos_libc_tests",
    srcs = ["tests/libc_tests.rs"],
    crate_name = "bexos_libc_tests",
    edition = "2024",
    env = {"RUST_TEST_THREADS": "1"},
    deps = [":bexos_libc"],
)
