package(default_visibility = ["//visibility:public"])

exports_files([
    "BUILD.sdk.bazel",
    "MODULE.sdk.bazel",
    "c_helper.c",
    "driver.rs",
    "driver_replacement.rs",
    "driver.prototxt",
    "service.rs",
    "service_replacement.rs",
    "service.prototxt",
    "state.rs",
    "echo.fidl",
    "fixture_signer.key",
    "fixture_signer_public.prototxt",
    "native.prototxt",
    "native.rs",
    "wasm.prototxt",
    "wasm.rs",
])
