load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "zircon",
    srcs = glob(["src/*.rs"]),
    crate_name = "bexos_zircon",
    edition = "2024",
    deps = [
        "//idl:kernel_fidl_rust",
        "//lib/userspace",
    ],
)

rust_test(name = "tests", crate = ":zircon")
