load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "e2e",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "bexos_e2e",
    edition = "2024",
    deps = [
        "//host/debug_client",
        "//host/trace_analysis",
        "//lib/trace",
    ],
)

rust_test(
    name = "e2e_tests",
    crate = ":e2e",
)
