load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "text_input",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "bexos_ui_text_input",
    edition = "2024",
    deps = [
        "//lib/dioxus_dom",
        "//lib/ui/core",
    ],
)

rust_test(
    name = "tests",
    crate = ":text_input",
)
